'use client';
import {useState} from 'react';
type Chunk={chunk:string;sound:string;cue:string};
type Word={en:string;zh:string;hint?:string;phonics?:Chunk[]};
export default function LearningCourse({words,onBack,onTest}:{words:Word[];onBack:()=>void;onTest:()=>void}){
 const [index,setIndex]=useState(0),[status,setStatus]=useState('点击播放单词'),[playing,setPlaying]=useState('');
 const word=words[index],chunks=word.phonics||word.en.split('').map(c=>({chunk:c,sound:'',cue:c}));
 function speak(text:string){setPlaying(text);setStatus('正在加载：'+text);const a=new Audio('https://dict.youdao.com/dictvoice?audio='+encodeURIComponent(text)+'&type=2');a.onplaying=()=>setStatus('🔊 正在播放：'+text);const fallback=()=>{setStatus('在线音频不可用，尝试设备语音');if('speechSynthesis'in window){window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='en-US';u.rate=.75;window.speechSynthesis.speak(u)}else setStatus('当前设备不支持语音播放')};a.onerror=fallback;a.play().catch(fallback)}
 if(!word)return null;
 return <section className="learning"><button className="back" onClick={onBack}>← 返回学习中心</button><div className="learnTop"><div><small>PHONICS · 自然拼读学习课</small><h1>先学会，再闯关</h1><p>第 {index+1} / {words.length} 个单词 · 看图、听音、分段拼读</p></div><span className="learnProgress">{Math.round((index+1)/words.length*100)}%</span></div><div className="wordCard"><div className="picture">{({sheep:'🐑',school:'🏫',teacher:'👩‍🏫',friend:'🤝',beautiful:'🌸'} as Record<string,string>)[word.en]||'📚'}</div><div className="wordInfo"><span className="learnBadge">今日新词</span><h2>{word.en}</h2><div className="ipa">{({sheep:'/ʃiːp/',school:'/skuːl/',teacher:'/ˈtiːtʃər/',friend:'/frend/',beautiful:'/ˈbjuːtɪfəl/'} as Record<string,string>)[word.en]||'点击听标准读音'}</div><p>{word.zh}</p><button className="purpleButton" onClick={()=>speak(word.en)}>▶ 播放完整单词</button></div></div><div className="phonicsPanel"><div className="sectionTitle"><h3>🔤 音素拆分 · 点一下，听一听</h3><small>字母组合和实际发音对应</small></div><div className="chunkGrid">{chunks.map((c,i)=><button key={i} className="chunk" onClick={()=>speak(c.cue)}><strong>{c.chunk}</strong><span>{c.sound||'🔊'}</span><small>点击发音</small></button>)}</div><p className="soundState" aria-live="polite">{status}{playing?'':''}</p><div className="learnActions"><button onClick={()=>speak(word.en)}>🔊 整词跟读</button><button onClick={()=>speak(word.en)}>🔁 再听一遍</button></div></div><div className="learnBottom"><button className="back" disabled={index===0} onClick={()=>setIndex(n=>n-1)}>← 上一个</button><span>学完之后进入闯关测试</span><button className="purpleButton" onClick={()=>index===words.length-1?onTest():setIndex(n=>n+1)}>{index===words.length-1?'开始闯关 →':'学会了，下一个 →'}</button></div><p className="footnote">示范词提供人工配置的自然拼读拆分；导入单词目前提供整词朗读和逐字母学习，自动音标与音素生成将在后续版本接入。</p></section>
}